info:
  version: testing
  stage: test

logging:
  file: target/boot-admin-sample.log

spring:
  application:
    name: spring-boot-admin-sample
  boot:
    admin:
      url: http://localhost:8080
  cloud:
    config:
      enabled: false
  jackson:
    serialization:
     indent-output: true

endpoints:
  health:
    sensitive: false